version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mahdy-backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    # Removed the unnecessary volumes mapping for logs
    # volumes:
    #   - backend-logs:/var/log/app
    networks:
      - mahdy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mahdy-frontend
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      # This log volume mapping is correct for Nginx logs
      - frontend-logs:/var/log/nginx
    networks:
      - mahdy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mahdy-network:
    driver: bridge
    name: mahdy-network

volumes:
  backend-logs:
    driver: local
  frontend-logs:
    driver: local