version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mahdy-backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - mahdy-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mahdy-frontend
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - frontend-logs:/var/log/nginx
    networks:
      - mahdy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mahdy-network:
    driver: bridge
    name: mahdy-network

volumes:
  frontend-logs:
    driver: local
