version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/mahdy-backend:${BACKEND_TAG:-latest}
    container_name: mahdy-backend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost:8080
    networks:
      - mahdy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${DOCKERHUB_USERNAME}/mahdy-frontend:${FRONTEND_TAG:-latest}
    container_name: mahdy-frontend-prod
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mahdy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mahdy-network:
    driver: bridge
    name: mahdy-network

volumes:
  backend-logs:
    driver: local
  frontend-logs:
    driver: local
