name: Manual Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      backend_tag:
        description: 'Backend image tag (default: latest)'
        required: false
        default: 'latest'
        type: string
      frontend_tag:
        description: 'Frontend image tag (default: latest)'
        required: false
        default: 'latest'
        type: string
      push_to_registry:
        description: 'Push to Docker Hub'
        required: false
        default: true
        type: boolean

env:
  DOCKER_REGISTRY: docker.io
  BACKEND_IMAGE: mahdy-backend
  FRONTEND_IMAGE: mahdy-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: ${{ github.event.inputs.push_to_registry == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: ${{ github.event.inputs.push_to_registry == 'true' }}
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ github.event.inputs.backend_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: ${{ github.event.inputs.push_to_registry == 'true' }}
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ github.event.inputs.frontend_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Backend Image: ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ github.event.inputs.backend_tag }}" >> $GITHUB_STEP_SUMMARY
        echo "- Frontend Image: ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ github.event.inputs.frontend_tag }}" >> $GITHUB_STEP_SUMMARY
        echo "- Push to Registry: ${{ github.event.inputs.push_to_registry }}" >> $GITHUB_STEP_SUMMARY
